### ISSUE TITLE
[Bug] hysteria 配置转换问题

### ISSUE THREAD

**Issue by fbewivpjsbsby** [lonelam/subconverter-rs#37]
### 问题描述
当 `type: hysteria` 时，若转换前 up, down 带 Mbps 会少参数，clash 会报错 up down 参数不存在
无论如何都会不存在参数 alpn
相关文件 https://github.com/lonelam/subconverter-rs/blob/main/src/generator/yaml/clash/output_proxy_types/clash_output_hysteria.rs#L22
使用的是官方部署 https://subconverter-rs.netlify.app
以及，clash 能不能别一出错整个订阅都没法用

### 复现步骤
转换前
```yaml
  - {name: serves, server: 192.168.1.1, port: 62003, type: hysteria, auth_str: auth, auth-str: auth, up: 1000 Mbps, down: 1000 Mbps, protocol: none, skip-cert-verify: true, alpn: [h3]}
```

转换后
```yaml
- type: hysteria
  name: server
  server: 192.168.1.1
  port: 62003
  skip-cert-verify: true
  protocol: none
  auth-str: auth
```

### 预期行为
转换后存在 up down 参数
