### ISSUE TITLE
vmess节点转换问题

### ISSUE THREAD

**Issue by Jonnyan404** [lonelam/subconverter-rs#40]
- 原始信息
```
  - {"name":"vmess-日本1","type":"vmess","server":"tokyo1.aaa.top","port":10000,"uuid":"b445361a-abcf-aaaa-a97a-0bf4136d6ddc","alterId":0,"cipher":"auto","udp":true,"tls":true,"network":"ws","ws-opts":{"path":"/b445361a-abcf-aaaa-a97a-0bf4136d6ddc-vm","headers":{"Host":"tokyo1.aaa.top"}},"servername":"tokyo1.aaa.top"}
```

- 转换后
```
- type: vmess
  name: 🇯🇵 vmess-日本1
  server: tokyo1.aaa.com
  port: 10000
  uuid: b445361a-abcf-aaaa-a97a-0bf4136d6ddc
  alterId: 0
  cipher: auto
  network: ws
  ws-opts:
    path: /b445361a-abcf-aaaa-a97a-0bf4136d6ddc-vm
    headers:
      Host: tokyo1.aaa.com
```

# 问题

转换丢失参数,导致不通
